name: rw_debouncer
description: A lightweight and efficient debouncing library for dart.
version: 1.0.0
repository: https://github.com/gbrandtio/rw-debouncer

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
